/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import game.XOGame;
import game.XOMatrix;
import game.XOPlayer;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pavel
 */
public class XOFrame extends javax.swing.JFrame {

    /**
     * Creates new form XOFrame
     */
    
    protected XOMatrix xoMatrix = null;
    protected XOGame xoGame = new XOGame();
            
    public XOFrame() {
        initComponents();
        initComponentsPost();

        xoMatrix = new XOMatrix();
        //xoMatrix = new XOMatrix(xoPanel);
        
    }

    private void initComponentsPost () {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        dsStats.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        dsStats.getColumnModel().getColumn(0).setMaxWidth(25);

    }
    
    private void displayNowTurn (XOPlayer player) {
               
        lblTurmValue.setForeground(player.getColor());
        lblTurmValue.setText(player.getName());
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xoPlayerChooser = new javax.swing.JDialog();
        lblPlayerOne = new javax.swing.JLabel();
        tfPlayerOne = new javax.swing.JTextField();
        lblPlayerTwo = new javax.swing.JLabel();
        tfPlayerTwo = new javax.swing.JTextField();
        btnPlayerOk = new javax.swing.JButton();
        btnPlayerCancel = new javax.swing.JButton();
        xoNextGame = new javax.swing.JDialog();
        lblCongratsTo = new javax.swing.JLabel();
        lblPlayerName = new javax.swing.JLabel();
        lblWinner = new javax.swing.JLabel();
        lblNumber = new javax.swing.JLabel();
        lblNumberValue = new javax.swing.JLabel();
        lblPressOk = new javax.swing.JLabel();
        btnNextGameOk = new javax.swing.JButton();
        xoPronGame = new javax.swing.JDialog();
        lblNoWinner = new javax.swing.JLabel();
        lblPronOk = new javax.swing.JLabel();
        btnProneGameOk = new javax.swing.JButton();
        xoGamePane = new javax.swing.JSplitPane();
        xoMatrixPanel = new javax.swing.JPanel();
        L00 = new javax.swing.JLabel();
        L01 = new javax.swing.JLabel();
        L02 = new javax.swing.JLabel();
        L10 = new javax.swing.JLabel();
        L11 = new javax.swing.JLabel();
        L12 = new javax.swing.JLabel();
        L20 = new javax.swing.JLabel();
        L21 = new javax.swing.JLabel();
        L22 = new javax.swing.JLabel();
        xoStats = new javax.swing.JPanel();
        lblGame = new javax.swing.JLabel();
        lblGameNr = new javax.swing.JLabel();
        lblTurm = new javax.swing.JLabel();
        lblTurmValue = new javax.swing.JLabel();
        tblStats = new javax.swing.JScrollPane();
        dsStats = new javax.swing.JTable();
        xoScore = new javax.swing.JPanel();
        lblScoreP1 = new javax.swing.JLabel();
        lblScoreP1value = new javax.swing.JLabel();
        lblScoreP2value = new javax.swing.JLabel();
        lblScoreP2 = new javax.swing.JLabel();
        xoMenuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        mNew = new javax.swing.JMenuItem();
        mExit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        mPlayers = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        mHowToPlay = new javax.swing.JMenuItem();
        mAbout = new javax.swing.JMenuItem();

        xoPlayerChooser.setTitle("Set player names");
        xoPlayerChooser.setName("xoPlayerChooser"); // NOI18N
        xoPlayerChooser.setType(java.awt.Window.Type.POPUP);

        lblPlayerOne.setText("Player's One name:");

        lblPlayerTwo.setText("Player's Two name:");

        btnPlayerOk.setText("Ok");
        btnPlayerOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayerOkActionPerformed(evt);
            }
        });

        btnPlayerCancel.setText("Cancel");
        btnPlayerCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayerCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout xoPlayerChooserLayout = new javax.swing.GroupLayout(xoPlayerChooser.getContentPane());
        xoPlayerChooser.getContentPane().setLayout(xoPlayerChooserLayout);
        xoPlayerChooserLayout.setHorizontalGroup(
            xoPlayerChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xoPlayerChooserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(xoPlayerChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(xoPlayerChooserLayout.createSequentialGroup()
                        .addComponent(lblPlayerOne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfPlayerOne))
                    .addGroup(xoPlayerChooserLayout.createSequentialGroup()
                        .addComponent(lblPlayerTwo)
                        .addGap(10, 10, 10)
                        .addGroup(xoPlayerChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(xoPlayerChooserLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btnPlayerOk)
                                .addGap(46, 46, 46)
                                .addComponent(btnPlayerCancel))
                            .addComponent(tfPlayerTwo, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))))
                .addContainerGap())
        );
        xoPlayerChooserLayout.setVerticalGroup(
            xoPlayerChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xoPlayerChooserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(xoPlayerChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlayerOne)
                    .addComponent(tfPlayerOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(xoPlayerChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlayerTwo)
                    .addComponent(tfPlayerTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(xoPlayerChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlayerOk)
                    .addComponent(btnPlayerCancel))
                .addContainerGap())
        );

        xoNextGame.setTitle("Congrats!!!");
        xoNextGame.setName("xoNextGame"); // NOI18N

        lblCongratsTo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCongratsTo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCongratsTo.setText("Cograts to player");

        lblPlayerName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPlayerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayerName.setText("Player");

        lblWinner.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblWinner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWinner.setText("winner of the game");

        lblNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNumber.setText("#");

        lblNumberValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNumberValue.setText("#");

        lblPressOk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPressOk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPressOk.setText("Press OK to continue");

        btnNextGameOk.setText("OK");
        btnNextGameOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextGameOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout xoNextGameLayout = new javax.swing.GroupLayout(xoNextGame.getContentPane());
        xoNextGame.getContentPane().setLayout(xoNextGameLayout);
        xoNextGameLayout.setHorizontalGroup(
            xoNextGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xoNextGameLayout.createSequentialGroup()
                .addGroup(xoNextGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(xoNextGameLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(xoNextGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCongratsTo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(xoNextGameLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblPressOk, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(xoNextGameLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnNextGameOk))
                    .addGroup(xoNextGameLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(lblNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNumberValue)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        xoNextGameLayout.setVerticalGroup(
            xoNextGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xoNextGameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCongratsTo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(xoNextGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumberValue)
                    .addComponent(lblNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPressOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNextGameOk)
                .addGap(5, 5, 5))
        );

        xoPronGame.setName("xoProneGame"); // NOI18N

        lblNoWinner.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNoWinner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoWinner.setText("Nobody won this time");

        lblPronOk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPronOk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPronOk.setText("Press OK to continue");

        btnProneGameOk.setText("OK");
        btnProneGameOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProneGameOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout xoPronGameLayout = new javax.swing.GroupLayout(xoPronGame.getContentPane());
        xoPronGame.getContentPane().setLayout(xoPronGameLayout);
        xoPronGameLayout.setHorizontalGroup(
            xoPronGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xoPronGameLayout.createSequentialGroup()
                .addGroup(xoPronGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(xoPronGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblPronOk, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(xoPronGameLayout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(lblNoWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(xoPronGameLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnProneGameOk)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        xoPronGameLayout.setVerticalGroup(
            xoPronGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xoPronGameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNoWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPronOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProneGameOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("XO Game");
        setMinimumSize(new java.awt.Dimension(400, 300));
        setName("xoFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 370));
        setResizable(false);

        xoGamePane.setBorder(null);
        xoGamePane.setDividerLocation(315);
        xoGamePane.setDividerSize(0);
        xoGamePane.setPreferredSize(new java.awt.Dimension(700, 350));

        xoMatrixPanel.setMaximumSize(new java.awt.Dimension(360, 360));
        xoMatrixPanel.setMinimumSize(new java.awt.Dimension(360, 360));
        xoMatrixPanel.setPreferredSize(new java.awt.Dimension(360, 360));
        xoMatrixPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                xoMatrixPanelKeyPressed(evt);
            }
        });
        xoMatrixPanel.setLayout(null);

        L00.setFont(new java.awt.Font("Tahoma", 0, 56)); // NOI18N
        L00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L00.setAlignmentX(0.5F);
        L00.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        L00.setFocusable(false);
        L00.setMaximumSize(new java.awt.Dimension(110, 110));
        L00.setMinimumSize(new java.awt.Dimension(110, 110));
        L00.setName("L00"); // NOI18N
        L00.setPreferredSize(new java.awt.Dimension(110, 110));
        L00.setRequestFocusEnabled(false);
        L00.setVerifyInputWhenFocusTarget(false);
        xoMatrixPanel.add(L00);
        L00.setBounds(10, 10, 100, 100);

        L01.setFont(new java.awt.Font("Tahoma", 0, 56)); // NOI18N
        L01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L01.setAlignmentX(0.5F);
        L01.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        L01.setFocusable(false);
        L01.setMaximumSize(new java.awt.Dimension(110, 110));
        L01.setMinimumSize(new java.awt.Dimension(110, 110));
        L01.setName("L01"); // NOI18N
        L01.setPreferredSize(new java.awt.Dimension(110, 110));
        L01.setRequestFocusEnabled(false);
        L01.setVerifyInputWhenFocusTarget(false);
        xoMatrixPanel.add(L01);
        L01.setBounds(10, 110, 100, 100);

        L02.setFont(new java.awt.Font("Tahoma", 0, 56)); // NOI18N
        L02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L02.setAlignmentX(0.5F);
        L02.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        L02.setFocusable(false);
        L02.setMaximumSize(new java.awt.Dimension(110, 110));
        L02.setMinimumSize(new java.awt.Dimension(110, 110));
        L02.setName("L02"); // NOI18N
        L02.setPreferredSize(new java.awt.Dimension(110, 110));
        L02.setRequestFocusEnabled(false);
        L02.setVerifyInputWhenFocusTarget(false);
        xoMatrixPanel.add(L02);
        L02.setBounds(10, 210, 100, 100);

        L10.setFont(new java.awt.Font("Tahoma", 0, 56)); // NOI18N
        L10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L10.setAlignmentX(0.5F);
        L10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        L10.setFocusable(false);
        L10.setMaximumSize(new java.awt.Dimension(110, 110));
        L10.setMinimumSize(new java.awt.Dimension(110, 110));
        L10.setName("L10"); // NOI18N
        L10.setPreferredSize(new java.awt.Dimension(110, 110));
        L10.setRequestFocusEnabled(false);
        L10.setVerifyInputWhenFocusTarget(false);
        xoMatrixPanel.add(L10);
        L10.setBounds(110, 10, 100, 100);

        L11.setFont(new java.awt.Font("Tahoma", 0, 56)); // NOI18N
        L11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L11.setAlignmentX(0.5F);
        L11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        L11.setFocusable(false);
        L11.setMaximumSize(new java.awt.Dimension(110, 110));
        L11.setMinimumSize(new java.awt.Dimension(110, 110));
        L11.setName("L11"); // NOI18N
        L11.setPreferredSize(new java.awt.Dimension(110, 110));
        L11.setRequestFocusEnabled(false);
        L11.setVerifyInputWhenFocusTarget(false);
        xoMatrixPanel.add(L11);
        L11.setBounds(110, 110, 100, 100);

        L12.setFont(new java.awt.Font("Tahoma", 0, 56)); // NOI18N
        L12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L12.setAlignmentX(0.5F);
        L12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        L12.setFocusable(false);
        L12.setMaximumSize(new java.awt.Dimension(110, 110));
        L12.setMinimumSize(new java.awt.Dimension(110, 110));
        L12.setName("L12"); // NOI18N
        L12.setPreferredSize(new java.awt.Dimension(110, 110));
        L12.setRequestFocusEnabled(false);
        L12.setVerifyInputWhenFocusTarget(false);
        xoMatrixPanel.add(L12);
        L12.setBounds(110, 210, 100, 100);

        L20.setFont(new java.awt.Font("Tahoma", 0, 56)); // NOI18N
        L20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L20.setAlignmentX(0.5F);
        L20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        L20.setFocusable(false);
        L20.setMaximumSize(new java.awt.Dimension(110, 110));
        L20.setMinimumSize(new java.awt.Dimension(110, 110));
        L20.setName("L20"); // NOI18N
        L20.setPreferredSize(new java.awt.Dimension(110, 110));
        L20.setRequestFocusEnabled(false);
        L20.setVerifyInputWhenFocusTarget(false);
        xoMatrixPanel.add(L20);
        L20.setBounds(210, 10, 100, 100);

        L21.setFont(new java.awt.Font("Tahoma", 0, 56)); // NOI18N
        L21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L21.setAlignmentX(0.5F);
        L21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        L21.setFocusable(false);
        L21.setMaximumSize(new java.awt.Dimension(110, 110));
        L21.setMinimumSize(new java.awt.Dimension(110, 110));
        L21.setName("L21"); // NOI18N
        L21.setPreferredSize(new java.awt.Dimension(110, 110));
        L21.setRequestFocusEnabled(false);
        L21.setVerifyInputWhenFocusTarget(false);
        xoMatrixPanel.add(L21);
        L21.setBounds(210, 110, 100, 100);

        L22.setFont(new java.awt.Font("Tahoma", 0, 56)); // NOI18N
        L22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L22.setAlignmentX(0.5F);
        L22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        L22.setFocusable(false);
        L22.setMaximumSize(new java.awt.Dimension(110, 110));
        L22.setMinimumSize(new java.awt.Dimension(110, 110));
        L22.setName("L22"); // NOI18N
        L22.setPreferredSize(new java.awt.Dimension(110, 110));
        L22.setRequestFocusEnabled(false);
        L22.setVerifyInputWhenFocusTarget(false);
        xoMatrixPanel.add(L22);
        L22.setBounds(210, 210, 100, 100);

        xoGamePane.setLeftComponent(xoMatrixPanel);

        xoStats.setPreferredSize(new java.awt.Dimension(270, 320));
        xoStats.setLayout(null);

        lblGame.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGame.setText("Game");
        lblGame.setFocusable(false);
        xoStats.add(lblGame);
        lblGame.setBounds(5, 5, 154, 17);

        lblGameNr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGameNr.setText("#");
        lblGameNr.setFocusable(false);
        xoStats.add(lblGameNr);
        lblGameNr.setBounds(169, 5, 91, 17);

        lblTurm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTurm.setForeground(new java.awt.Color(0, 0, 153));
        lblTurm.setText("Now turn:");
        lblTurm.setFocusable(false);
        xoStats.add(lblTurm);
        lblTurm.setBounds(5, 28, 62, 15);

        lblTurmValue.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTurmValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTurmValue.setText("Who's next?");
        lblTurmValue.setFocusable(false);
        xoStats.add(lblTurmValue);
        lblTurmValue.setBounds(85, 28, 175, 15);

        tblStats.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        dsStats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "#", "Winner"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dsStats.setFocusable(false);
        dsStats.setRowMargin(2);
        tblStats.setViewportView(dsStats);
        if (dsStats.getColumnModel().getColumnCount() > 0) {
            dsStats.getColumnModel().getColumn(0).setResizable(false);
            dsStats.getColumnModel().getColumn(0).setPreferredWidth(25);
        }

        xoStats.add(tblStats);
        tblStats.setBounds(5, 54, 255, 186);

        xoScore.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblScoreP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScoreP1.setText("P1");

        lblScoreP1value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScoreP1value.setText("0");

        lblScoreP2value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScoreP2value.setText("0");

        lblScoreP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScoreP2.setText("P2");

        javax.swing.GroupLayout xoScoreLayout = new javax.swing.GroupLayout(xoScore);
        xoScore.setLayout(xoScoreLayout);
        xoScoreLayout.setHorizontalGroup(
            xoScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xoScoreLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lblScoreP1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblScoreP1value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblScoreP2value, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblScoreP2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        xoScoreLayout.setVerticalGroup(
            xoScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xoScoreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(xoScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblScoreP1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xoScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblScoreP2)
                        .addComponent(lblScoreP2value)
                        .addComponent(lblScoreP1value)))
                .addGap(25, 25, 25))
        );

        xoStats.add(xoScore);
        xoScore.setBounds(10, 250, 250, 40);

        xoGamePane.setRightComponent(xoStats);

        getContentPane().add(xoGamePane, java.awt.BorderLayout.CENTER);

        menuFile.setText("Game");

        mNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mNew.setText("New");
        mNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNewActionPerformed(evt);
            }
        });
        menuFile.add(mNew);

        mExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mExit.setText("Exit");
        mExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mExitActionPerformed(evt);
            }
        });
        menuFile.add(mExit);

        xoMenuBar.add(menuFile);

        menuEdit.setText("Edit");

        mPlayers.setText("Players");
        mPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPlayersActionPerformed(evt);
            }
        });
        menuEdit.add(mPlayers);

        xoMenuBar.add(menuEdit);

        menuHelp.setText("Help");

        mHowToPlay.setText("How to play");
        menuHelp.add(mHowToPlay);

        mAbout.setText("About");
        menuHelp.add(mAbout);

        xoMenuBar.add(menuHelp);

        setJMenuBar(xoMenuBar);

        getAccessibleContext().setAccessibleName("Game XO frame");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayerCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayerCancelActionPerformed
        // TODO add your handling code here:
        //tfPlayerOne.setText("");
        //tfPlayerTwo.setText("");
        xoPlayerChooser.setVisible(false); //setVisible(false);
    }//GEN-LAST:event_btnPlayerCancelActionPerformed

    private void mExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mExitActionPerformed

    private void mPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPlayersActionPerformed
        // TODO add your handling code here:
        tfPlayerOne.setText(xoGame.p1.getName());
        tfPlayerTwo.setText(xoGame.p2.getName());
        xoPlayerChooser.pack();
        xoPlayerChooser.setLocationRelativeTo(this);
        xoPlayerChooser.setVisible(true); //setVisible(true); // show();
    }//GEN-LAST:event_mPlayersActionPerformed

    private void mNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNewActionPerformed
        xoMatrix.Initialize(xoMatrixPanel);
        xoGame.startOver();            
        
        lblGameNr.setText(Integer.toString(xoGame.count)); 
        this.displayNowTurn(xoGame.getPlayer());
        
        DefaultTableModel tModel = (DefaultTableModel) dsStats.getModel();
        tModel.setRowCount(0);
        
        xoMatrixPanel.requestFocus();
    }//GEN-LAST:event_mNewActionPerformed

    private void btnPlayerOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayerOkActionPerformed
        // TODO add your handling code here:
        if (!tfPlayerOne.getText().equals("")) {
            xoGame.p1.setName(tfPlayerOne.getText());
            //xoTable.getColumnModel().getColumn(1).setHeaderValue(tfPlayerOne.getText());
        }
        if (!tfPlayerTwo.getText().equals("")) {
            xoGame.p2.setName(tfPlayerTwo.getText());
            //xoTable.getColumnModel().getColumn(2).setHeaderValue(tfPlayerTwo.getText());
        }
        this.displayNowTurn(xoGame.getPlayer());
        tblStats.repaint();
        xoPlayerChooser.setVisible(false);
    }//GEN-LAST:event_btnPlayerOkActionPerformed

    private void btnNextGameOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextGameOkActionPerformed
        // TODO add your handling code here:
        xoMatrix.Initialize(xoMatrixPanel);
        xoGame.nextGame();
        lblGameNr.setText(Integer.toString(xoGame.count)); 
        this.displayNowTurn(xoGame.getPlayer());
        
        xoNextGame.setVisible(false);
        xoMatrixPanel.requestFocus();
    }//GEN-LAST:event_btnNextGameOkActionPerformed

    private void btnProneGameOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProneGameOkActionPerformed
        // TODO add your handling code here:
        xoMatrix.Initialize(xoMatrixPanel);
        xoGame.nextGame();
        lblGameNr.setText(Integer.toString(xoGame.count));         
        this.displayNowTurn(xoGame.getPlayer());        

        xoPronGame.setVisible(false);        
        xoMatrixPanel.requestFocus();      
    }//GEN-LAST:event_btnProneGameOkActionPerformed

    private void xoMatrixPanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xoMatrixPanelKeyPressed
        //System.out.println(evt.getKeyCode());
        if ( xoGame.count > 0 && xoGame.active ) {
            if (evt.getKeyCode() == 32) { // space bar pressed
                XOPlayer player  = xoGame.getPlayer();

                if ( xoMatrix.setSign(player) ) {

                    if (player.getCounter() > 2 && xoMatrix.checkWinner(player)) {
                        xoGame.active = false;
                        xoGame.addStats(dsStats, true);

                        lblPlayerName.setText(player.getName());
                        lblPlayerName.setForeground(player.getColor());
                        lblNumberValue.setText(Integer.toString(xoGame.count));
                        xoNextGame.pack();
                        xoNextGame.setLocationRelativeTo(this);
                        xoNextGame.setVisible(true);

                    } else if (xoMatrix.getCount() == 9 && !xoMatrix.checkWinner(player)) {
                        xoGame.active = false;
                        xoGame.addStats(dsStats, false);
                        xoPronGame.pack();
                        xoPronGame.setLocationRelativeTo(this);
                        xoPronGame.setVisible(true);

                    } else {

                        this.displayNowTurn(xoGame.nowTurn());

                    }
                }

            } else {
                xoMatrix.setMove(evt.getKeyCode());
            }
        }
    }//GEN-LAST:event_xoMatrixPanelKeyPressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(XOFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(XOFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(XOFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(XOFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new XOFrame().setVisible(true);
//            }
//        });
//    }
    
    //<editor-fold defaultstate="collapsed" desc=" Variables declaration - do not modify ">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L00;
    private javax.swing.JLabel L01;
    private javax.swing.JLabel L02;
    private javax.swing.JLabel L10;
    private javax.swing.JLabel L11;
    private javax.swing.JLabel L12;
    private javax.swing.JLabel L20;
    private javax.swing.JLabel L21;
    private javax.swing.JLabel L22;
    private javax.swing.JButton btnNextGameOk;
    private javax.swing.JButton btnPlayerCancel;
    private javax.swing.JButton btnPlayerOk;
    private javax.swing.JButton btnProneGameOk;
    private javax.swing.JTable dsStats;
    private javax.swing.JLabel lblCongratsTo;
    private javax.swing.JLabel lblGame;
    private javax.swing.JLabel lblGameNr;
    private javax.swing.JLabel lblNoWinner;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblNumberValue;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JLabel lblPlayerOne;
    private javax.swing.JLabel lblPlayerTwo;
    private javax.swing.JLabel lblPressOk;
    private javax.swing.JLabel lblPronOk;
    private javax.swing.JLabel lblScoreP1;
    private javax.swing.JLabel lblScoreP1value;
    private javax.swing.JLabel lblScoreP2;
    private javax.swing.JLabel lblScoreP2value;
    private javax.swing.JLabel lblTurm;
    private javax.swing.JLabel lblTurmValue;
    private javax.swing.JLabel lblWinner;
    private javax.swing.JMenuItem mAbout;
    private javax.swing.JMenuItem mExit;
    private javax.swing.JMenuItem mHowToPlay;
    private javax.swing.JMenuItem mNew;
    private javax.swing.JMenuItem mPlayers;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JScrollPane tblStats;
    private javax.swing.JTextField tfPlayerOne;
    private javax.swing.JTextField tfPlayerTwo;
    private javax.swing.JSplitPane xoGamePane;
    private javax.swing.JPanel xoMatrixPanel;
    private javax.swing.JMenuBar xoMenuBar;
    private javax.swing.JDialog xoNextGame;
    private javax.swing.JDialog xoPlayerChooser;
    private javax.swing.JDialog xoPronGame;
    private javax.swing.JPanel xoScore;
    private javax.swing.JPanel xoStats;
    // End of variables declaration//GEN-END:variables
//</editor-fold>
}
